mixed-port: 7890
authentication: [""]
allow-lan: true
mode: rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090
external-ui: ui
secret: 
tcp-concurrent: true
global-client-fingerprint: chrome
geodata-mode: true 
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb"
profile:
  store-selected: true
  store-fake-ip: true
find-process-mode: strict

tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
  auto-detect-interface: true
  auto-route: true 
  strict-route: true

sniffer: 
  enable: false
  skip-domain: 
    - Mijia Cloud
  sniff: 
    TLS: 
      ports: [443, 8443]
    HTTP: 
      ports: [80, 8080-8880]
      override-destination: true

hosts:
  'time.android.com': 203.107.6.88
  'time.facebook.com': 203.107.6.88  
  'localhost': 127.0.0.1

dns:
  enable: true
  prefer-h3: true
  ipv6: true
  listen: 0.0.0.0:1053
  use-hosts: true
  enhanced-mode: fake-ip # redir-host
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - "*"
    - "+.lan"
  default-nameserver:
    - 192.168.1.1
  nameserver:
    - 8.8.8.8
    - 2001:4860:4860::8888
    - 208.67.222.222
    - 2620:0:ccc::2
  nameserver-policy:
    'geosite:cn,private,apple,microsoft': 
      - 192.168.1.1
      - 2400:3200::1

# 锚点
p: &p
  type: http
  interval: 3600
  health-check:
    enable: true
    url: "http://www.gstatic.com/generate_204"
    interval: 300
n: &n
  type: url-test
  interval: 300
  tolerance: 50
  url: "http://www.gstatic.com/generate_204"

# 自建节点
proxies: 
  - name: "Wireguard-US"
    type: wireguard
    server: 23.94.73.197
    port: 56505
    ip: 10.66.66.2
    ipv6: fd42:42:42::2
    public-key: jflbUStuJmxcqqXnoQhzKBJeCszfi9GpTMaAlxBpPjs=
    pre-shared-key: dVvIwuHZcMoTDelYs9ZztZz5yJN9T3EcH6Gf8eyZadY=
    private-key: YAP8zVvkF9KzOpJw9UqLDjnjoRUhit/Lqd+7CymPoHo=
    udp: true
    # reserved: "U4An"
    remote-dns-resolve: true
    dns: [ 1.1.1.1, 1.0.0.1 ]
  
  - name: "Hysteria-US"
    type: hysteria
    server: 23.94.73.197
    port: 5200
    auth_str: 8JCsPssfgS8tiRwiMlhARg==
    alpn:
      - h3
    protocol: udp
    up: 300
    down: 300
    sni: sing-box.nvshen.pro
    skip-cert-verify: true
    recv_window_conn: 15728640
    recv_window: 67108864
    disable_mtu_discovery: true
    fast-open: true
  
  - name: "Hysteria-JP"
    type: hysteria
    server: "2a12:bec0:166:5fb::"
    port: 10086
    auth_str: k1ENkP16w1G6Go7rN5TfgnwcTMzcXB9G6PGckjO52MPtJeRrQs
    alpn:
      - h3
    protocol: udp
    up: 88
    down: 396
    sni: v2ray.nvshen.pro
    skip-cert-verify: false
    recv_window_conn: 64749568
    recv_window: 258998272
    disable_mtu_discovery: true
    fast-open: true
  
  - name: "Hysteria-TW"
    type: hysteria
    server: 2001:b030:a42d:5d00::ffff:169
    port: 10040
    auth_str: 8JCsPssfgS8tiRwiMlhARg==
    alpn:
      - h3
    protocol: udp
    up: 80
    down: 240
    sni: sing-box.nvshen.pro
    skip-cert-verify: true
    recv_window_conn: 15728640
    recv_window: 67108864
    disable_mtu_discovery: true
    fast-open: true
    ip-version: ipv6-prefer
  
  - name: "Shaowsocks-TW"
    type: ss
    server: 2001:b030:a42d:5d00::ffff:169
    port: 10030
    cipher: 2022-blake3-aes-128-gcm
    password: "8JCsPssfgS8tiRwiMlhARg=="
    udp: true

  - name: "Shaowsocks-US"
    type: ss
    server: 23.94.73.197
    port: 9090
    cipher: 2022-blake3-aes-128-gcm
    password: "8JCsPssfgS8tiRwiMlhARg=="
    udp: true

  - name: "Trojan-US"
    type: trojan
    server: 23.94.73.197.nip.io
    port: 443
    password: "8JCsPssfgS8tiRwiMlhARg=="
    udp: true
    sni: 23.94.73.197.nip.io
    alpn:
      - h2
      - http/1.1
    skip-cert-verify: false

  - name: "Trojan-grpc-TW"
    server: 2001:b030:a42d:5d00::ffff:169
    port: 10010
    type: trojan
    password: "chika"
    network: grpc
    sni: sing-box.nvshen.pro
    skip-cert-verify: true
    udp: true
    grpc-opts:
      grpc-service-name: "lovelive"
  
  - name: "Tuic-US"
    type: tuic
    server: 23.94.73.197
    port: 23333
    token: 8JCsPssfgS8tiRwiMlhARg==
    udp: true
    skip-cert-verify: true
    sni: 23.94.73.197.nip.io
    alpn:
      - h3
    reduce-rtt: true
    udp-relay-mode: quic # Available: "native", "quic". Default: "native"
    congestion-controller: bbr # Available: "cubic", "new_reno", "bbr". Default: "cubic"
    # fast-open: true
  
  - name: "Tuic-TW"
    type: tuic
    server: 2001:B030:A42D:5D00::FFFF:169
    port: 23333
    token: 8JCsPssfgS8tiRwiMlhARg==
    udp: true
    skip-cert-verify: true
    sni: 23.94.73.197.nip.io
    alpn:
      - h3
    reduce-rtt: true
    udp-relay-mode: native
    max-udp-relay-packet-size: 1146
    congestion-controller: bbr
  
  - name: "Tuic-JP"
    type: tuic
    server: "2a12:bec0:166:5fb::"
    port: 23333
    token: 8JCsPssfgS8tiRwiMlhARg==
    udp: true
    skip-cert-verify: true
    sni: 23.94.73.197.nip.io
    alpn:
      - h3
    reduce-rtt: true
    udp-relay-mode: native 
    max-udp-relay-packet-size: 1146
    congestion-controller: bbr
    ip-version: ipv6-prefer 
  
  - name: "ShadowTLS-TW"
    type: ss
    server: 2001:B030:A42D:5D00::FFFF:169
    port: 10020
    cipher: 2022-blake3-aes-128-gcm
    password: "3P+xaSaFiXsrQ1KCr2Xvxg=="
    plugin: shadow-tls
    client-fingerprint: chrome
    plugin-opts:
      host: "www.lovelive-anime.jp"
      password: "chika"
      version: 3 # support 1/2/3
  
  - name: "Vless-reality-grpc-TW"
    type: vless
    server: 2001:B030:A42D:5D00::FFFF:169
    port: 7820
    uuid: ee9a733e-ffb3-45bf-8cc5-93f194011614
    network: grpc
    tls: true
    udp: true
    flow:
    # skip-cert-verify: true
    client-fingerprint: chrome
    servername: itunes.apple.com
    grpc-opts:
      grpc-service-name: "clashmeta"
    reality-opts:
      public-key: -F_y5898PrpuRpkUuWqEACl4QR8A_WIcGgsJH1jj43w
      short-id: 3783daa0b21cbe3e
 
  - name: "Vless-CF-HK"
    type: vless
    server: 103.200.112.206 #34.92.10.35 #129.154.206.46 #vless-lc.nvshen.pro #vless-tw.nvshen.pro #35.215.129.156 #cf.nvshen.pro 103.200.112.206
    port: 443
    uuid: b7625108-80fb-4544-a1f2-aa40c931aa52
    udp: true
    tls: true
    network: ws
    ws-opts:
      path: "/vless"
      headers:
        Host: cf.nvshen.pro
  
  - name: "Vless-WK"
    type: vless
    server: 104.16.107.110
    port: 80
    uuid: 82d5348b-7164-460f-bd7f-4b941b334536
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: vless.wecheney.workers.dev
  
  - name: "Vless-CF-JP"
    type: vless
    server: 116.206.93.26 #18.180.211.35 #nrt.chigua.tk #47.74.34.249 #vless-lc.nvshen.pro #vless-tw.nvshen.pro #35.215.129.156 #cf.nvshen.pro
    port: 443
    uuid: b7625108-80fb-4544-a1f2-aa40c931aa52
    udp: true
    tls: true
    network: ws
    ws-opts:
      path: "/vless"
      headers:
        Host: cf.nvshen.pro

  - name: "Vmess-JP"
    type: vmess
    server: 104.16.107.110
    port: 80
    uuid: 3c1890e2-c768-4247-8a3b-032f6ed13a64
    alterId: 0
    cipher: auto
    udp: true
    network: ws
    ws-opts:
      path: /stream
      headers:
        Host: v2ray.nvshen.pro
    
  - name: "Vmess-US"
    type: vmess
    server: cdn.anycast.eu.org #104.16.107.110
    port: 80
    uuid: 3c1890e2-c768-4247-8a3b-032f6ed13a64
    alterId: 0
    cipher: auto
    udp: true
    network: ws
    ws-opts:
      path: /stream
      headers:
        Host: sing-box.nvshen.pro
  
  - name: "Vmess-HK"
    type: vmess
    server: 104.16.107.110 #cdn.anycast.eu.org #104.16.107.110
    port: 80
    uuid: 3c1890e2-c768-4247-8a3b-032f6ed13a64
    alterId: 0
    cipher: auto
    udp: true
    network: ws
    ws-opts:
      path: /stream
      headers:
        Host: hkbgp.nvshen.pro
  
  - name: "Vmess-UJP"
    type: vmess
    server: 104.16.107.110 #cdn.anycast.eu.org #104.16.107.110
    port: 80
    uuid: 3c1890e2-c768-4247-8a3b-032f6ed13a64
    alterId: 0
    cipher: auto
    udp: true
    network: ws
    ws-opts:
      path: /stream
      headers:
        Host: ujp.nvshen.pro

# 机场
proxy-providers:
  CLCat:
    <<: *p
    url: "https://www.miaowu.ml/api/convert?url=https%3A%2F%2Fpdd.msclm.net%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3D87667ac5538637b857b61052504cb8ea&target=clash" 
    path: ./proxy_providers/CLCat.yaml 
  EFCloud:
    <<: *p
    url: "https://www.miaowu.ml/api/convert?url=https%3A%2F%2Fv1.efshop.cc%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3Db8fa5377d966a1f448850abe8779dacc&target=clash" 
    path: ./proxy_providers/EFCloud.yaml
  WenLianYun:
    <<: *p
    url: "https://www.miaowu.ml/api/convert?url=https%3A%2F%2Fdingyue.wenlianyun.vip%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3D23634537e3c242814edca9811cbe72e9%26security%3Dd8cd98f00b204e980&target=clash" 
    path: ./proxy_providers/WenLianYun.yaml
  YiYuan:
    <<: *p
    url: "https://www.miaowu.ml/api/convert?url=https%3A%2F%2Fsub1.smallstrawberry.com%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3D8df72d000c34d88bc854c2bb58d3f9c7&target=clash" 
    path: ./proxy_providers/YiYuan.yaml
  SiHaiYun:
    <<: *p
    url: "https://www.miaowu.ml/api/convert?url=https%3A%2F%2Fv2b.lol%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3Df98a2182616fe9542c9f4c62b695e1da&target=clash"
    # "https://www.miaowu.ml/api/convert?url=http%3A%2F%2Fsub.sihaiyun.vip%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3Dd5bb0c0c193d933fbe937725f42a855e&target=clash" 
    path: ./proxy_providers/SiHaiYun.yaml
  NodPai:
    <<: *p
    url: "https://www.miaowu.ml/api/convert?url=https%3A%2F%2Fsub.pmsub.me%2Fclash.yaml&target=clash" 
    path: ./proxy_providers/Nodpai.yaml

# 策略组
proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - 香港节点Ⅰ
      - 香港节点Ⅱ
      - 日本节点Ⅰ
      - 日本节点Ⅱ
      - 新加坡节点Ⅰ
      - 新加坡节点Ⅱ
      - 韩国节点Ⅰ
      - 韩国节点Ⅱ
      - 無料Ⅰ
      - 無料Ⅱ
      - Download
      - Myself
      - NodPai
      - DIRECT

# 香港节点
  - name: 香港节点Ⅰ
    <<: *n
    filter: 香港
    use:
      - CLCat
  - name: 香港节点Ⅱ
    <<: *n
    filter: 香港
    use:
      - EFCloud

# 日本节点
  - name: 日本节点Ⅰ
    <<: *n
    filter: 日本
    use:
      - CLCat
  - name: 日本节点Ⅱ
    <<: *n
    filter: 日本
    use:
      - EFCloud

# 新加坡节点
  - name: 新加坡节点Ⅰ
    <<: *n
    filter: 新加坡
    use:
      - CLCat
  - name: 新加坡节点Ⅱ
    <<: *n
    filter: 新加坡
    use:
      - EFCloud

# 韩国节点
  - name: 韩国节点Ⅰ
    <<: *n
    filter: 韩国
    use:
      - CLCat
  - name: 韩国节点Ⅱ
    <<: *n
    filter: 韩国
    use:
      - EFCloud

# 白嫖节点
  - name: 無料Ⅰ
    type: select
    filter: 日本|新加坡|香港
    use:
      - WenLianYun
  - name: 無料Ⅱ
    type: select
    use:
      - SiHaiYun

# 大流量下载节点
  - name: Download
    type: select
    filter: 日本|新加坡|香港
    use:
      - YiYuan
  
  # 公益节点 @NodPai
  - name: NodPai
    type: select
    filter: 日本|Japan|新加坡|Singapore|香港|Hong Kong
    use:
      - NodPai

# 自建节点
  - name: Myself
    type: select
    proxies:
      - Wireguard-US
      - Hysteria-US
      - Hysteria-TW
      - Hysteria-JP
      - Shaowsocks-US
      - Shaowsocks-TW
      - ShadowTLS-TW
      - Trojan-US
      - Trojan-grpc-TW
      - Vless-reality-grpc-TW
      - Tuic-TW
      - Tuic-US
      - Tuic-JP
      - Vless-CF-HK
      - Vmess-JP
      - Vless-CF-JP
      - Vmess-US
      - Vmess-HK
      - Vmess-UJP
      - Vless-WK

# Media(TikTok&Netflix)
  - name: Media
    type: select
    proxies:
      - PROXY
    filter: 日本
    use:
      - EFCloud
      - CLCat

# DMM
  - name: DMM
    type: select
    filter: 日本|JP
    proxies:
      - PROXY
      - Hysteria-JP
      - Vless-CF-JP
    use:
      - EFCloud

# PikPak
  - name: PikPak
    type: select
    proxies:
      - PROXY
      - Download
      - 無料Ⅱ

# JavDB
  - name: JavDB
    type: select
    proxies:
      - PROXY
      - 香港节点Ⅰ
      - 香港节点Ⅱ

# Porn
  - name: Porn
    type: select
    proxies:
      - PROXY
      - 日本节点Ⅰ
      - 日本节点Ⅱ

# Google
  - name: Google
    type: select
    proxies:
      - PROXY
      - 無料Ⅱ

# 规则
rules:
  - DOMAIN,yacd.metacubex.one,DIRECT
  - AND,((DOMAIN-SUFFIX,jp),(NOT,((GEOSITE,dmm)))),DMM
  - DOMAIN-SUFFIX,mypikpak.com,PikPak
  - DOMAIN-SUFFIX,aisee.tv,DIRECT
  - GEOSITE,github,PROXY
  - GEOSITE,apple,DIRECT
  - GEOSITE,microsoft,DIRECT
  - GEOSITE,netflix,Media
  - GEOSITE,dmm,DMM
  - GEOSITE,javdb,JavDB
  - GEOSITE,category-porn,Porn
  - GEOSITE,tiktok,Media
  - GEOSITE,google,Google
  - GEOSITE,telegram,PROXY
  - GEOSITE,twitter,PROXY
  - GEOSITE,facebook,PROXY
  - GEOIP,google,Google
  - GEOIP,facebook,PROXY
  - GEOIP,telegram,PROXY
  - GEOIP,twitter,PROXY
  - GEOIP,jp,DMM
  - GEOIP,fastly,PROXY
  - GEOIP,cloudflare,Tuic-TW
  - GEOIP,cloudfront,Tuic-TW
  - GEOSITE,geolocation-!cn,PROXY
  - GEOSITE,private,DIRECT
  - GEOSITE,cn,DIRECT
  - GEOIP,private,DIRECT
  - GEOIP,cn,DIRECT
  - DST-PORT,123/136/137-139/445,DIRECT
  - IP-CIDR,10.233.0.0/16,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - MATCH,PROXY
